### ISSUE TITLE
add /alias command

### ISSUE THREAD

**Issue by tunnckoCore** [moose-team/friends#107]
and yea, would be good to follow irc signature

**Comment by ngoldman** [comment]
This isn't compatible with the way we're handling authentication and signing for the moment -- we're using github usernames and public keys so that identities are in some way verified.

**Comment by pokemonmegaman** [comment]
@ngoldman I think that he's referring to command aliases, as per http://www.ircbeginner.com/ircinfo/h-aliases.html .  I imagine the syntax for an `alias` command would be something along the lines of `/alias <alias name> <command to execute>` so that a command/string of commands/long message could be easily sent.  For example,  `/alias foo /join bar` would make `/foo` run the `/join bar` command.  Additionally,  frequently used chat messages could be done this way, such as `/alias hello Hello world!` would cause the command `hello` to send "Hello world!" to the channel.

**Comment by ngoldman** [comment]
ah ok, I think I misinterpreted it as a `/nick` thing :sweat:

**Comment by tunnckoCore** [comment]
>  I think that he's referring to command aliases

yes, exactly. one more link http://www.mirchelp.net/helpfile/aliases.htm

> ah ok, I think I misinterpreted it as a /nick thing

ha, but you have right in your previous comment. the problem is where to save this aliases per session (per user). i guess leveldb is only used for message/channel logs? if we start using the db and for users and their aliases... it wouldn't be good thing.

**Comment by ngoldman** [comment]
`localStorage` would work for now

**Comment by tunnckoCore** [comment]
ha, good idea, I forgot it.
